// Reference taxonomy only; labels and descriptions are written for Beaver.
// See docs/ui/PROJECT_BLUEPRINT.md for provenance and the prototype boundary.
export const catalogSource =
  "https://github.com/binogure-studio/city-game-studio-i18n/blob/9a23d7a097df1f9560afbb536afb6f051ed30d38/languages/zh.yml";

export const genreChoices = [
  ["RTT", "即时战术", "策略"],
  ["4X", "4X 战略", "策略"],
  ["ACTION_ADVENTURE", "动作冒险", "动作"],
  ["ACTION", "动作", "动作"],
  ["BEAT_THEM_ALL", "清版动作", "动作"],
  ["VERSUS_FIGHTING", "对战格斗", "动作"],
  ["PLATFORMS", "平台跳跃", "动作"],
  ["SHOOT", "射击", "动作"],
  ["SHOOT_EM_UP", "飞行射击", "动作"],
  ["FPS", "第一人称射击", "动作"],
  ["TPS", "第三人称射击", "动作"],
  ["HACK_N_SLASH", "砍杀动作", "动作"],
  ["OPEN_WORLD", "开放世界", "探索"],
  ["HTA_LIKE", "都市犯罪沙盒", "探索"],
  ["INFILTRATION", "潜行", "探索"],
  ["SURVIVAL", "生存", "探索"],
  ["HORROR", "恐怖冒险", "探索"],
  ["ADVENTURE", "冒险", "探索"],
  ["INTERACTIVE_FICTION", "互动小说", "叙事"],
  ["INTERACTIVE_MOVIE", "互动电影", "叙事"],
  ["CHAT", "社交聊天", "叙事"],
  ["BISHOJO", "美少女叙事", "叙事"],
  ["EROGE", "成人向视觉小说", "叙事"],
  ["OTOME", "乙女向叙事", "叙事"],
  ["VISUAL_NOVEL", "视觉小说", "叙事"],
  ["MYSTERY_LIKE", "推理悬疑", "叙事"],
  ["RPG", "角色扮演", "角色扮演"],
  ["ACTION_RPG", "动作角色扮演", "角色扮演"],
  ["DUNGEON_CRAWLER", "地城探索", "角色扮演"],
  ["MMORPG", "大型多人在线角色扮演", "角色扮演"],
  ["DUNGEON", "地下城", "角色扮演"],
  ["CROOK_LIKE", "Roguelike", "角色扮演"],
  ["TACTICAL_RPG", "战术角色扮演", "角色扮演"],
  ["REFLEXION", "益智", "休闲"],
  ["MAZE", "迷宫", "休闲"],
  ["HIDDEN_OBJECT", "寻物", "休闲"],
  ["PUZZLE", "解谜", "休闲"],
  ["SIMULATION", "模拟", "模拟经营"],
  ["ANIMALS", "动物模拟", "模拟经营"],
  ["GOD_GAME", "上帝模拟", "模拟经营"],
  ["FARMING", "农场模拟", "模拟经营"],
  ["LIVING_ORGANISM", "生命模拟", "模拟经营"],
  ["SPORT", "体育", "模拟经营"],
  ["MANAGEMENT", "经营管理", "模拟经营"],
  ["ECONOMY", "经济模拟", "模拟经营"],
  ["CITY_BUILDER", "城市建造", "模拟经营"],
  ["GOVERNMENT", "政务模拟", "模拟经营"],
  ["VEHICLE", "交通载具", "载具"],
  ["RACING", "竞速", "载具"],
  ["DRIVE", "驾驶模拟", "载具"],
  ["FLY", "飞行模拟", "载具"],
  ["SPACE", "太空模拟", "载具"],
  ["SUBMARINE", "潜艇模拟", "载具"],
  ["TRAIN", "铁路模拟", "载具"],
  ["STRATEGY", "策略", "策略"],
  ["RTS", "即时战略", "策略"],
  ["MOBA_LIKE", "MOBA", "策略"],
  ["TOWER_DEFENSE", "塔防", "策略"],
  ["TURN_BASED", "回合制策略", "策略"],
  ["ARTILLERY", "炮术对战", "策略"],
  ["CASUAL", "休闲", "休闲"],
  ["BREAKOUT", "打砖块", "休闲"],
  ["RYTHM", "音乐节奏", "休闲"],
  ["CLICKER_GAME", "放置点击", "休闲"],
].map(([key, name, group]) => ({
  id: key!.toLowerCase().replaceAll("_", "-"),
  name: name!,
  group: group!,
  sourceKey: `LABEL_TYPE_${key}`,
}));

export const themeChoices = [
  ["MOVIE_ADAPTATION", "影视改编"],
  ["PREHISTORY", "史前世界"],
  ["ARCHEOLOGY", "考古探索"],
  ["POSTAPOCALYPTIC", "末日之后"],
  ["ATLANTIS", "失落文明"],
  ["RELIGIOUS", "宗教文化"],
  ["ORGANIZED_CRIME", "犯罪组织"],
  ["CROSSOVER", "跨题材混合"],
  ["DESERT", "沙漠"],
  ["COMEDY", "喜剧"],
  ["DRAGON", "龙与传说"],
  ["EROTIC", "成人情感"],
  ["SPY", "谍报"],
  ["FANTASY", "奇幻"],
  ["GHOST", "幽灵"],
  ["HISTORY", "历史"],
  ["HORROR", "惊悚恐怖"],
  ["MEDICAL", "医疗"],
  ["OCEAN", "海洋"],
  ["ARABIAN_NIGHTS", "天方夜谭"],
  ["MYTHOLOGY", "神话"],
  ["NINJA", "忍者"],
  ["PARK", "游乐园"],
  ["PIRATES", "海盗"],
  ["SCIENCE_FICTION", "科幻"],
  ["SUPER_HEROS", "超级英雄"],
  ["VAMPIRE", "吸血鬼"],
  ["TIME_TRAVEL", "时空旅行"],
  ["WESTERN", "西部"],
  ["ZOMBIE", "丧尸"],
  ["MEDIEVAL", "中世纪"],
  ["GAMEDEV", "游戏开发"],
  ["HACK", "黑客"],
  ["HUNT", "狩猎"],
  ["ANIME", "动画风格世界"],
  ["MILITARY", "军事"],
  ["INDUSTRIALIZATION", "工业时代"],
  ["PET", "宠物"],
  ["FOOTBALL", "美式橄榄球"],
  ["SOCCER", "足球"],
  ["CARTOON", "卡通世界"],
  ["COOK", "料理"],
  ["URBAN", "现代都市"],
  ["KAIJU", "巨兽"],
  ["EVOLUTION", "生命进化"],
  ["CYBERPUNK", "赛博朋克"],
  ["STEAMPUNK", "蒸汽朋克"],
  ["TRANSPORTATION", "交通运输"],
  ["MUSIC", "音乐"],
].map(([key, name]) => ({
  id: key!.toLowerCase().replaceAll("_", "-"),
  name: name!,
  sourceKey: `LABEL_THEME_${key}`,
}));

export const audiences = [
  {
    id: "all",
    name: "全年龄",
    meaning:
      "面向广泛受众。素材以温和表达为目标，避免血腥、露骨性内容与强烈恐怖。",
  },
  {
    id: "young",
    name: "青少年",
    meaning: "可讨论成长、冲突与适度紧张情节；避免露骨性内容和细节化残酷描绘。",
  },
  {
    id: "mature",
    name: "成年人",
    meaning:
      "允许更复杂沉重的主题与较强冲突表达；仍须明确内容边界，不解除服务安全限制。",
  },
] as const;
export const gameSizes = [
  {
    id: "indie",
    name: "独立",
    meaning: "少量系统与紧凑内容，优先验证一个完整核心循环。",
  },
  {
    id: "normal",
    name: "标准",
    meaning: "多个相互配合的系统，形成较完整的关卡或章节体验。",
  },
  {
    id: "big",
    name: "大型",
    meaning: "较多内容、系统与资产，未来需要分批制作和持续验收。",
  },
  {
    id: "aaa",
    name: "AAA",
    meaning: "最高复杂度的长期制作目标；不代表预算、团队、质量或工期已经具备。",
  },
] as const;

export const phases = [
  {
    id: "design",
    name: "设计",
    metrics: [
      {
        id: "story",
        name: "故事性",
        meaning: "世界观、叙事结构、分支与结局的投入重点。",
        output: "故事大纲、章节节拍、分支条件与文本约束。",
        acceptance: "剧情与玩法相互支持，关键分支能到达明确结果。",
      },
      {
        id: "characters",
        name: "角色",
        meaning: "角色动机、关系、造型与语言一致性的投入重点。",
        output: "角色设定、关系图、立绘和对白规范。",
        acceptance: "角色可辨认，行为与视觉表现不自相矛盾。",
      },
      {
        id: "gameplay",
        name: "游戏性",
        meaning: "核心循环、规则、反馈、胜负与难度的投入重点。",
        output: "玩法规则、操作流程和核心循环原型目标。",
        acceptance: "玩家清楚能做什么、为何行动以及得到什么反馈。",
      },
      {
        id: "graphics",
        name: "图像",
        meaning: "游戏内视觉风格、材质、光照与素材一致性的投入重点。",
        output: "风格板、素材规格、场景视觉基准。",
        acceptance: "运行画面的可读性与风格一致，区别于后期宣传插画。",
      },
      {
        id: "ui",
        name: "用户界面",
        meaning: "游戏内信息层级、菜单、HUD 与输入反馈的投入重点。",
        output: "界面流程、HUD 布局与键鼠/手柄交互稿。",
        acceptance: "关键操作容易发现，不遮挡玩法或遗漏错误状态。",
      },
    ],
  },
  {
    id: "development",
    name: "开发",
    metrics: [
      {
        id: "physics",
        name: "物理",
        meaning: "碰撞、运动、接触反馈与模拟稳定性的投入重点。",
        output: "碰撞与运动规则、边界案例测试目标。",
        acceptance: "常见操作不穿透、不抖动，行为符合玩法约定。",
      },
      {
        id: "ai",
        name: "人工智能",
        meaning: "游戏内 NPC、敌人和策略行为，不是 Beaver 的模型服务。",
        output: "行为状态、决策规则与可调难度方案。",
        acceptance: "角色行为可解释且可测试，不出现持续卡死。",
      },
      {
        id: "sound",
        name: "声音",
        meaning: "音乐、音效、语音、混音与触发规则的投入重点。",
        output: "音频清单、声音风格与播放/混音约定。",
        acceptance: "听觉反馈与操作匹配，音量稳定且素材有使用权。",
      },
      {
        id: "modding",
        name: "模组",
        meaning: "玩家扩展游戏内容的接口与数据结构，不是本应用功能块商店。",
        output: "扩展边界、数据格式、装载和版本约定。",
        acceptance: "扩展失败可诊断，不破坏基础游戏与存档。",
      },
      {
        id: "network",
        name: "网络",
        meaning: "联机状态同步、房间、鉴权、断线恢复与服务协议。",
        output: "网络拓扑、同步模型、房间流程与压力测试目标。",
        acceptance: "按目标人数验证延迟与恢复；规划数字不当成压测结果。",
      },
    ],
  },
  {
    id: "post",
    name: "后期",
    metrics: [
      {
        id: "animation",
        name: "动画",
        meaning: "角色、环境和交互动画的表现与衔接。",
        output: "动画清单、状态切换与事件同步规范。",
        acceptance: "动作衔接自然，动画事件与玩法状态一致。",
      },
      {
        id: "optimization",
        name: "优化",
        meaning: "帧率、内存、加载、包体与不同设备表现。",
        output: "性能预算、基准场景与优化清单。",
        acceptance: "使用真实设备测量目标，而不是仅显示完成标记。",
      },
      {
        id: "artwork",
        name: "插画",
        meaning: "封面、宣传图、章节插画等独立成图内容。",
        output: "插画规格、构图需求和渠道尺寸变体。",
        acceptance: "符合游戏风格和目标评级，关键主体在各尺寸下清楚。",
      },
      {
        id: "tutorial",
        name: "教程",
        meaning: "新玩家学习规则、首次操作与提示节奏。",
        output: "新手路径、逐步提示和跳过/重看方案。",
        acceptance: "首次游玩能够理解核心操作，不强迫重复教学。",
      },
      {
        id: "cutscenes",
        name: "过场动画",
        meaning: "叙事演出、镜头、字幕和与玩法的进出衔接。",
        output: "分镜、镜头时序、字幕及跳过规则。",
        acceptance: "可跳过、不丢关键状态，并与存档恢复兼容。",
      },
    ],
  },
] as const;
export const campaignChoices = [
  {
    id: "press",
    name: "联系媒体发布",
    meaning: "准备简介、截图、媒体包和联系名单；未来经确认后对外发送。",
    outputs: "媒体包、联系人与发送记录",
    channels: ["游戏媒体", "评测作者", "内容创作者"],
  },
  {
    id: "demo",
    name: "发布试玩版",
    meaning:
      "划定可玩内容、构建试玩包、检查存档隔离与反馈入口；未来再发布到渠道。",
    outputs: "试玩构建、渠道资料与反馈入口",
    channels: ["itch.io", "Steam", "自有页面"],
  },
  {
    id: "advertising",
    name: "进行广告宣传",
    meaning: "规划受众、素材、渠道与预算；未来单独确认投放，不自动花费。",
    outputs: "宣传素材、排期与待批准预算",
    channels: ["社交媒体", "视频平台", "广告网络"],
  },
] as const;
